version: "1"
name: my-app
description: Minimal Taskfile example

variables:
  APP: my-app
  TAG: latest

tasks:
  test:
    desc: Run tests
    stage: test
    tags: [ci, quality]
    cmds:
      - pytest -v

  build:
    desc: Build Docker image
    stage: build
    tags: [ci, build]
    deps: [test]
    cmds:
      - docker build -t ${APP}:${TAG} .

  run:
    desc: Run locally
    cmds:
      - docker run --rm -p 3000:3000 ${APP}:${TAG}

  all:
    desc: Run full pipeline
    deps: [test, build]
    parallel: false
