"""Interactive wizard helpers and commands — doctor, init with choices, env detection."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import clickmd as click
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt, IntPrompt

from taskfile.cli.main import console, main
from taskfile.cli.diagnostics import ProjectDiagnostics
from taskfile.parser import load_taskfile, find_taskfile, TaskfileNotFoundError, TaskfileParseError


def _detect_project_type() -> str:
    """Detect project type from files in directory."""
    if Path("pyproject.toml").exists() or Path("setup.py").exists():
        return "python"
    if Path("package.json").exists():
        return "nodejs"
    if Path("Cargo.toml").exists():
        return "rust"
    if Path("go.mod").exists():
        return "go"
    if Path("composer.json").exists():
        return "php"
    return "generic"


def _suggest_template(project_type: str) -> str:
    """Suggest template based on project type."""
    suggestions = {
        "python": "full",
        "nodejs": "web",
        "rust": "minimal",
        "go": "minimal",
        "php": "web",
        "generic": "minimal",
    }
    return suggestions.get(project_type, "minimal")


def _collect_env_config_interactive() -> dict[str, str]:
    """Collect environment configuration interactively."""
    config = {}

    console.print(Panel.fit(
        "[bold green]Environment Configuration[/]\n[dim]Press Enter to skip or use defaults[/]",
        border_style="green"
    ))

    # Detect defaults from environment
    default_domain = os.environ.get("DOMAIN", "localhost")
    default_port = os.environ.get("PORT", "8000")

    config["DOMAIN"] = Prompt.ask("Domain", default=default_domain)
    config["PORT"] = str(IntPrompt.ask("Port", default=int(default_port)))

    # API Keys
    if Confirm.ask("Configure OpenRouter?", default=False):
        api_key = Prompt.ask("OPENROUTER_API_KEY", default=os.environ.get("OPENROUTER_API_KEY", ""))
        config["OPENROUTER_API_KEY"] = api_key

    # Deployment hosts
    if Confirm.ask("Configure deployment hosts?", default=False):
        console.print("\n[dim]Staging environment:[/]")
        config["STAGING_HOST"] = Prompt.ask("  Staging host", default="staging.example.com")
        config["STAGING_USER"] = Prompt.ask("  Staging user", default="deploy")

        console.print("\n[dim]Production environment:[/]")
        config["PROD_HOST"] = Prompt.ask("  Production host", default="prod.example.com")
        config["PROD_USER"] = Prompt.ask("  Production user", default="deploy")

    return config


def _write_env_file(config: dict[str, str], env_name: str = "local") -> None:
    """Write environment file."""
    filename = f".env.{env_name}" if env_name != "local" else ".env"
    filepath = Path(filename)

    lines = [f"# Auto-generated by taskfile init\n"]
    for key, value in sorted(config.items()):
        lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"

    if filepath.exists():
        if not Confirm.ask(f"{filename} exists. Overwrite?", default=False):
            console.print(f"[yellow]Skipping {filename}[/]")
            return

    filepath.write_text(content)
    console.print(f"[green]✓ Created {filename}[/]")


def _collect_init_choices() -> dict[str, any]:
    """Collect all init choices from user."""
    choices = {}

    # Project type detection
    project_type = _detect_project_type()
    suggested_template = _suggest_template(project_type)

    console.print(Panel.fit(
        f"[bold green]Taskfile Project Init[/]\n"
        f"[dim]Detected project type: {project_type}[/]",
        border_style="green"
    ))

    # Template selection with preview
    templates = {
        "minimal": "Basic build/deploy tasks",
        "web": "Web app with Docker + Traefik",
        "podman": "Podman Quadlet (low RAM)",
        "full": "All features, multi-env",
        "multiplatform": "Desktop+Web × Local+Prod",
        "publish": "Multi-registry publish",
        "kubernetes": "K8s + Helm multi-cluster",
        "terraform": "Terraform IaC multi-env",
        "iot": "IoT fleet with strategies",
    }

    console.print("\n[bold]Available templates:[/]")
    for key, desc in templates.items():
        marker = " [green]← suggested[/]" if key == suggested_template else ""
        console.print(f"  [cyan]{key:12}[/] — {desc}{marker}")

    choices["template"] = Prompt.ask(
        "\nSelect template",
        default=suggested_template,
        choices=list(templates.keys())
    )

    # Environment configuration
    if Confirm.ask("\nConfigure environment variables?", default=True):
        choices["env_config"] = _collect_env_config_interactive()
    else:
        choices["env_config"] = {}

    # Additional options
    choices["create_gitignore"] = Confirm.ask(
        "Create .gitignore?",
        default=not Path(".gitignore").exists()
    )

    choices["init_git"] = Confirm.ask(
        "Initialize git repository?",
        default=not Path(".git").exists()
    )

    return choices


def _create_gitignore() -> None:
    """Create sensible .gitignore."""
    content = """# Environment files
.env
.env.local
.env.prod
.env.staging

# Python
__pycache__/
*.pyc
.venv/
*.egg-info/
.pytest_cache/

# Node
node_modules/
dist/
build/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
"""
    Path(".gitignore").write_text(content)
    console.print("[green]✓ Created .gitignore[/]")


@main.command()
@click.option("--fix", is_flag=True, help="Auto-fix issues where possible")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@click.option("--report", is_flag=True, help="Output JSON report (for CI pipelines)")
@click.option("--examples", "check_examples_flag", is_flag=True, help="Validate all examples/ directories")
@click.option("--llm", is_flag=True, help="Ask AI for help on unresolved issues (requires pip install taskfile[llm])")
@click.option("--category", type=click.Choice(["config", "env", "infra", "runtime", "all"], case_sensitive=False), default="all", help="Filter by issue category")
def doctor(fix, verbose, report, check_examples_flag, llm, category):
    """**🔧 Diagnose project** — 5-layer self-healing diagnostics.

## Layers

| Layer | What it does |
|-------|--------------|
| 1. Preflight | Check if tools exist (docker, ssh, git) |
| 2. Validation | Check if Taskfile.yml is correct |
| 3. Diagnostics | Check environment health (ports, SSH, .env) |
| 4. Algorithmic fix | Auto-fix what can be fixed deterministically |
| 5. LLM assist | Ask AI for help on unresolved issues (optional) |

## Options

| Option | Description |
|--------|-------------|
| `--fix` | Auto-fix issues where possible (Layer 4) |
| `--llm` | Ask AI for suggestions on unresolved issues (Layer 5) |
| `--category` | Filter: config, env, infra, runtime, or all |
| `--report` | JSON output for CI pipelines |
| `--examples` | Validate all examples/ directories |

## Examples

```bash
# Full 5-layer diagnostics
taskfile doctor

# Auto-fix + AI suggestions
taskfile doctor --fix --llm

# Only config issues
taskfile doctor --category config

# JSON report for CI
taskfile doctor --report
```
"""
    diagnostics = ProjectDiagnostics()

    if not report:
        console.print(Panel.fit(
            "[bold blue]🔧 Taskfile Doctor[/]\n[dim]5-layer diagnostics...[/]",
            border_style="blue"
        ))

    with console.status("[bold green]Checking project...[/]") if not report else _nullcontext():
        # Layer 1: Preflight
        diagnostics.check_preflight()
        # Layer 2: Validation
        diagnostics.check_taskfile()
        # Layer 3: Diagnostics
        diagnostics.check_env_files()
        diagnostics.validate_taskfile_variables()
        diagnostics.check_dependent_files()
        diagnostics.check_ports()
        diagnostics.check_docker()
        diagnostics.check_ssh_keys()
        diagnostics.check_git()
        # Layer 3+: Task command checks (if verbose)
        if verbose:
            diagnostics.check_task_commands()
            diagnostics.check_ssh_connectivity()

    # Validate examples/ directory if requested
    if check_examples_flag:
        _run_examples_check(diagnostics, report)

    if report:
        diagnostics.print_report_json()
        sys.exit(1 if any(s == "error" for _, s, _ in diagnostics.issues) else 0)

    diagnostics.print_report()

    # Layer 4: Algorithmic fix
    if fix and diagnostics.issues:
        console.print("\n[bold]Layer 4: Attempting auto-fix...[/]")
        fixed = diagnostics.auto_fix()
        if fixed > 0:
            console.print(f"[green]✓ Fixed {fixed} issue(s)[/]")

    # Layer 5: LLM assist
    if llm and diagnostics._issues:
        _run_llm_assist(diagnostics)

    # Summary
    if not diagnostics.issues:
        console.print("\n[bold green]Your project is ready! 🚀[/]")
        console.print("\n[dim]Next steps:[/]")
        console.print("  taskfile list       — See available tasks")
        console.print("  taskfile run build  — Build your project")
    else:
        error_count = sum(1 for _, s, _ in diagnostics.issues if s == "error")
        if error_count > 0:
            console.print(f"\n[red]Found {error_count} error(s) that need attention[/]")
            sys.exit(1)


def _run_llm_assist(diagnostics: ProjectDiagnostics) -> None:
    """Layer 5: Ask LLM for suggestions on unresolved issues."""
    from taskfile.diagnostics.llm_repair import is_available as llm_available
    from taskfile.diagnostics.models import FixStrategy

    llm_issues = [i for i in diagnostics._issues if i.fix_strategy == FixStrategy.LLM]
    if not llm_issues:
        return

    if not llm_available():
        console.print("\n[yellow]Layer 5: LLM not available[/]")
        console.print("  Install with: [cyan]pip install taskfile[llm][/]")
        console.print(f"  ({len(llm_issues)} issue(s) could benefit from AI suggestions)")
        return

    console.print(f"\n[bold magenta]Layer 5: Asking AI about {len(llm_issues)} issue(s)...[/]")
    suggestions = diagnostics.llm_repair()
    for suggestion in suggestions:
        console.print(f"  💡 {suggestion}")


class _nullcontext:
    """Minimal no-op context manager for Python <3.10 compat."""
    def __enter__(self): return self
    def __exit__(self, *a): pass


def _run_examples_check(diagnostics: ProjectDiagnostics, report: bool) -> None:
    """Validate all examples/ directories and print results."""
    from taskfile.cli.diagnostics import IssueCategory

    examples_dir = Path("examples")
    if not examples_dir.is_dir():
        # Try relative to Taskfile
        try:
            tf = find_taskfile()
            examples_dir = tf.parent / "examples"
        except Exception:
            pass

    results = ProjectDiagnostics.check_examples(examples_dir)
    if not results:
        if not report:
            console.print("[yellow]No examples found to validate[/]")
        return

    if not report:
        from rich.table import Table
        from rich import box as rbox
        table = Table(title="Examples Validation", box=rbox.ROUNDED)
        table.add_column("Example", style="cyan")
        table.add_column("Tasks", justify="right")
        table.add_column("Envs", justify="right")
        table.add_column("Status")
        table.add_column("Missing .env files")

        for r in results:
            if r["errors"]:
                status = "[red]✗ Error[/]"
            elif r["missing_env_files"]:
                status = "[yellow]⚠ Warning[/]"
            else:
                status = "[green]✓ OK[/]"
            missing = ", ".join(r["missing_env_files"]) if r["missing_env_files"] else ""
            table.add_row(r["name"], str(r["tasks"]), str(r["envs"]), status, missing)

        console.print(table)

    # Add missing .env files as issues
    for r in results:
        for mf in r["missing_env_files"]:
            diagnostics._add_issue(
                f"Example '{r['name']}': missing {mf}",
                "warning", False, IssueCategory.ENV
            )
        for err in r["errors"]:
            diagnostics._add_issue(
                f"Example '{r['name']}': {err}",
                "error", False, IssueCategory.CONFIG
            )


def _apply_init_extras(choices: dict) -> None:
    """Write env files, .gitignore, and init git based on wizard choices."""
    env_config = choices.get("env_config") or {}
    if env_config:
        _write_env_file(env_config, "local")
        staging_config = {k: v for k, v in env_config.items() if "STAGING" in k or "PROD" in k}
        if staging_config and any(k.startswith("STAGING_") for k in env_config):
            _write_env_file(staging_config, "prod")

    if choices.get("create_gitignore"):
        _create_gitignore()

    if choices.get("init_git"):
        try:
            subprocess.run(["git", "init"], capture_output=True, check=True)
            console.print("[green]✓ Initialized git repository[/]")
        except Exception as e:
            console.print(f"[yellow]⚠ Git init failed: {e}[/]")


@main.command()
@click.option("--template", type=click.Choice([
    "minimal", "web", "podman", "codereview", "full",
    "multiplatform", "publish", "kubernetes", "terraform", "iot"
]), default=None, help="Project template")
@click.option("--force", is_flag=True, help="Overwrite existing files")
@click.option("--interactive", "-i", is_flag=True, help="Interactive setup with prompts")
def init(template, force, interactive):
    """**✨ Create a new Taskfile.yml** with interactive setup.

## Templates

| Template | Description |
|----------|-------------|
| `minimal` | Basic setup with build/test/run |
| `web` | Web application with Docker |
| `podman` | Podman/Quadlet deployment |
| `kubernetes` | K8s deployment |
| `full` | Complete CI/CD pipeline |

## Options

| Option | Description |
|--------|-------------|
| `--template` | Project template to use |
| `--force` | Overwrite existing files |
| `-i, --interactive` | Interactive setup with prompts |

## Examples

```bash
# Minimal template (default)
taskfile init

# Web app template
taskfile init --template web

# Full interactive setup
taskfile init -i

# Overwrite existing
taskfile init -i --force
```
"""
    outpath = Path("Taskfile.yml")

    if outpath.exists() and not force:
        console.print(f"[yellow]{outpath} already exists. Use --force to overwrite.[/]")
        if not Confirm.ask("Continue anyway?", default=False):
            sys.exit(1)

    # Interactive mode
    if interactive or template is None:
        choices = _collect_init_choices()
        template = choices["template"]
    else:
        choices = {"env_config": {}, "create_gitignore": False, "init_git": False}

    # Generate Taskfile
    from taskfile.scaffold import generate_taskfile
    content = generate_taskfile(template)
    outpath.write_text(content)
    console.print(f"[green]✓ Created Taskfile.yml (template: {template})[/]")

    _apply_init_extras(choices)

    # Summary
    console.print("\n[bold green]✨ Project initialized! 🚀[/]")
    console.print("\n[dim]Next steps:[/]")
    console.print("  taskfile doctor     — Check setup")
    console.print("  taskfile list       — See available tasks")
    console.print("  taskfile run build  — Build your project")
