"""Interactive wizard helpers and commands — doctor, init with choices, env detection."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import clickmd as click
from rich.panel import Panel
from rich.prompt import Confirm, Prompt, IntPrompt

from taskfile.cli.main import console, main
from taskfile.cli.diagnostics import ProjectDiagnostics
from taskfile.parser import load_taskfile, find_taskfile


def _detect_project_type() -> str:
    """Detect project type from files in directory."""
    if Path("pyproject.toml").exists() or Path("setup.py").exists():
        return "python"
    if Path("package.json").exists():
        return "nodejs"
    if Path("Cargo.toml").exists():
        return "rust"
    if Path("go.mod").exists():
        return "go"
    if Path("composer.json").exists():
        return "php"
    return "generic"


def _suggest_template(project_type: str) -> str:
    """Suggest template based on project type."""
    suggestions = {
        "python": "full",
        "nodejs": "web",
        "rust": "minimal",
        "go": "minimal",
        "php": "web",
        "generic": "minimal",
    }
    return suggestions.get(project_type, "minimal")


def _collect_env_config_interactive() -> dict[str, str]:
    """Collect environment configuration interactively."""
    config = {}

    console.print(
        Panel.fit(
            "[bold green]Environment Configuration[/]\n[dim]Press Enter to skip or use defaults[/]",
            border_style="green",
        )
    )

    # Detect defaults from environment
    default_domain = os.environ.get("DOMAIN", "localhost")
    default_port = os.environ.get("PORT", "8000")

    config["DOMAIN"] = Prompt.ask("Domain", default=default_domain)
    config["PORT"] = str(IntPrompt.ask("Port", default=int(default_port)))

    # API Keys
    if Confirm.ask("Configure OpenRouter?", default=False):
        api_key = Prompt.ask("OPENROUTER_API_KEY", default=os.environ.get("OPENROUTER_API_KEY", ""))
        config["OPENROUTER_API_KEY"] = api_key

    # Deployment hosts
    if Confirm.ask("Configure deployment hosts?", default=False):
        console.print("\n[dim]Staging environment:[/]")
        config["STAGING_HOST"] = Prompt.ask("  Staging host", default="staging.example.com")
        config["STAGING_USER"] = Prompt.ask("  Staging user", default="deploy")

        console.print("\n[dim]Production environment:[/]")
        config["PROD_HOST"] = Prompt.ask("  Production host", default="prod.example.com")
        config["PROD_USER"] = Prompt.ask("  Production user", default="deploy")

    return config


def _write_env_file(config: dict[str, str], env_name: str = "local") -> None:
    """Write environment file."""
    filename = f".env.{env_name}" if env_name != "local" else ".env"
    filepath = Path(filename)

    lines = ["# Auto-generated by taskfile init\n"]
    for key, value in sorted(config.items()):
        lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"

    if filepath.exists():
        if not Confirm.ask(f"{filename} exists. Overwrite?", default=False):
            console.print(f"[yellow]Skipping {filename}[/]")
            return

    filepath.write_text(content)
    console.print(f"[green]✓ Created {filename}[/]")


def _collect_init_choices() -> dict[str, any]:
    """Collect all init choices from user."""
    choices = {}

    # Project type detection
    project_type = _detect_project_type()
    suggested_template = _suggest_template(project_type)

    console.print(
        Panel.fit(
            f"[bold green]Taskfile Project Init[/]\n[dim]Detected project type: {project_type}[/]",
            border_style="green",
        )
    )

    # Template selection with preview
    templates = {
        "minimal": "Basic build/deploy tasks",
        "web": "Web app with Docker + Traefik",
        "podman": "Podman Quadlet (low RAM)",
        "full": "All features, multi-env",
        "saas": "SaaS app — hosts, deploy recipe, addons (120L)",
        "multiplatform": "Desktop+Web × Local+Prod",
        "publish": "Multi-registry publish",
        "kubernetes": "K8s + Helm multi-cluster",
        "terraform": "Terraform IaC multi-env",
        "iot": "IoT fleet with strategies",
    }

    console.print("\n[bold]Available templates:[/]")
    for key, desc in templates.items():
        marker = " [green]← suggested[/]" if key == suggested_template else ""
        console.print(f"  [cyan]{key:12}[/] — {desc}{marker}")

    choices["template"] = Prompt.ask(
        "\nSelect template", default=suggested_template, choices=list(templates.keys())
    )

    # Environment configuration
    if Confirm.ask("\nConfigure environment variables?", default=True):
        choices["env_config"] = _collect_env_config_interactive()
    else:
        choices["env_config"] = {}

    # Additional options
    choices["create_gitignore"] = Confirm.ask(
        "Create .gitignore?", default=not Path(".gitignore").exists()
    )

    choices["init_git"] = Confirm.ask(
        "Initialize git repository?", default=not Path(".git").exists()
    )

    return choices


def _create_gitignore() -> None:
    """Create sensible .gitignore."""
    content = """# Environment files
.env
.env.local
.env.prod
.env.staging

# Python
__pycache__/
*.pyc
.venv/
*.egg-info/
.pytest_cache/

# Node
node_modules/
dist/
build/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db
"""
    Path(".gitignore").write_text(content)
    console.print("[green]✓ Created .gitignore[/]")


@main.command()
@click.option("--fix", is_flag=True, help="Auto-fix issues where possible")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@click.option("--report", is_flag=True, help="Output JSON report (for CI pipelines)")
@click.option(
    "--examples", "check_examples_flag", is_flag=True, help="Validate all examples/ directories"
)
@click.option(
    "--llm",
    is_flag=True,
    help="Ask AI for help on unresolved issues (requires pip install taskfile[llm])",
)
@click.option(
    "--category",
    type=click.Choice(["config", "env", "infra", "runtime", "all"], case_sensitive=False),
    default="all",
    help="Filter by issue category",
)
@click.option("--teach", is_flag=True, help="Show educational explanations for each issue")
@click.option("--remote", is_flag=True, help="Run diagnostics on remote server (via SSH)")
@click.option("--quality", "quality_check", is_flag=True, help="Run pyqual code quality analysis")
@click.option(
    "--quality-fix", "quality_fix", is_flag=True, help="Auto-fix pyqual issues (implies --quality)"
)
def doctor(
    fix,
    verbose,
    report,
    check_examples_flag,
    llm,
    category,
    teach,
    remote,
    quality_check,
    quality_fix,
):
    """**🔧 Diagnose project** — 5-layer self-healing diagnostics.

## Layers

| Layer | What it does |
|-------|--------------|
| 1. Preflight | Check if tools exist (docker, ssh, git) |
| 2. Validation | Check if Taskfile.yml is correct |
| 3. Diagnostics | Check environment health (ports, SSH, .env) |
| 4. Algorithmic fix | Auto-fix what can be fixed deterministically |
| 5. LLM assist | Ask AI for help on unresolved issues (optional) |

## Options

| Option | Description |
|--------|-------------|
| `--fix` | Auto-fix issues where possible (Layer 4) |
| `--llm` | Ask AI for suggestions on unresolved issues (Layer 5) |
| `--category` | Filter: config, env, infra, runtime, or all |
| `--report` | JSON output for CI pipelines |
| `--examples` | Validate all examples/ directories |
| `--teach` | Show educational explanations for each issue |
| `--remote` | Run diagnostics on remote server via SSH |

## Examples

```bash
# Full 5-layer diagnostics
taskfile doctor

# Verbose mode (extra checks: task commands, SSH, remote health)
taskfile doctor -v

# Diagnostics on remote production server
taskfile --env prod doctor --remote

# Auto-fix + AI suggestions
taskfile doctor --fix --llm

# Only config issues
taskfile doctor --category config

# JSON report for CI
taskfile doctor --report

# Educational mode — learn why each issue matters
taskfile doctor --teach

# Production server via REST API (when taskfile api serve is running)
curl http://localhost:8000/doctor
curl -X POST http://localhost:8000/doctor -H "Content-Type: application/json" \
  -d '{"verbose": true, "fix": true}'
```
"""
    diagnostics = ProjectDiagnostics()

    if not report:
        console.print(
            Panel.fit(
                "[bold blue]🔧 Taskfile Doctor[/]\n[dim]5-layer diagnostics...[/]",
                border_style="blue",
            )
        )

    _doctor_run_checks(diagnostics, verbose=verbose, remote=remote, report=report)

    if quality_check or quality_fix:
        _doctor_run_quality_check(diagnostics, fix=quality_fix, report=report)

    if check_examples_flag:
        _run_examples_check(diagnostics, report)

    if report:
        diagnostics.print_report_json()
        sys.exit(1 if any(s == "error" for _, s, _ in diagnostics.issues) else 0)

    diagnostics.print_report(show_teach=teach)
    _doctor_apply_fixes(diagnostics, fix=fix, llm=llm)
    _doctor_print_summary(diagnostics)


def _doctor_run_checks(
    diagnostics: ProjectDiagnostics, *, verbose: bool, remote: bool, report: bool
) -> None:
    """Layers 1-3: Run all diagnostic checks (with optional spinner)."""
    with (
        console.status(
            "[bold green]Checking project...[/]"
            if not remote
            else "[bold green]Checking remote server...[/]"
        )
        if not report
        else _nullcontext()
    ):
        diagnostics.run_all_checks(verbose=verbose, remote=remote)
        if remote:
            _run_remote_diagnostics(diagnostics)


def _doctor_apply_fixes(diagnostics: ProjectDiagnostics, *, fix: bool, llm: bool) -> None:
    """Layers 4-5: Apply auto-fixes and optionally ask LLM for suggestions."""
    if fix and diagnostics.issues:
        console.print("\n[bold]Layer 4: Attempting auto-fix...[/]")
        fixed = diagnostics.auto_fix()
        if fixed > 0:
            console.print(f"[green]✓ Fixed {fixed} issue(s)[/]")

    if llm and diagnostics._issues:
        _run_llm_assist(diagnostics)


def _doctor_run_quality_check(diagnostics: ProjectDiagnostics, *, fix: bool, report: bool) -> None:
    """Run pyqual code quality analysis (Layer 3+)."""
    if not report:
        console.print("\n[bold blue]Layer 3+: Code Quality Analysis (pyqual)...[/]")

    # Check if pyqual is installed
    has_pyqual = diagnostics.check_pyqual_installed()

    if not has_pyqual and not report:
        console.print("[yellow]⚠ pyqual not installed — install with: pip install pyqual[/]")
        return

    if has_pyqual:
        diagnostics.check_pyqual_quality()

        if fix and not report:
            console.print("[bold]Applying pyqual auto-fixes...[/]")
            fixed, failed = diagnostics.fix_with_pyqual()
            if fixed > 0:
                console.print(f"[green]✓ Fixed {fixed} pyqual issue(s)[/]")
            if failed:
                console.print(f"[yellow]⚠ Could not fix {len(failed)} issue(s)[/]")


def _doctor_print_summary(diagnostics: ProjectDiagnostics) -> None:
    """Print final doctor summary with next-step guidance."""
    if not diagnostics.issues:
        console.print("\n[bold green]Your project is ready! 🚀[/]")
        console.print("\n[dim]Next steps:[/]")
        console.print("  taskfile list       — See available tasks")
        console.print("  taskfile run build  — Build your project")
    else:
        error_count = sum(1 for _, s, _ in diagnostics.issues if s == "error")
        if error_count > 0:
            console.print(f"\n[red]Found {error_count} error(s) that need attention[/]")
            sys.exit(1)


def _run_llm_assist(diagnostics: ProjectDiagnostics) -> None:
    """Layer 5: Ask LLM for suggestions on unresolved issues."""
    from taskfile.diagnostics.llm_repair import is_available as llm_available
    from taskfile.diagnostics.models import FixStrategy

    llm_issues = [i for i in diagnostics._issues if i.fix_strategy == FixStrategy.LLM]
    if not llm_issues:
        return

    if not llm_available():
        console.print("\n[yellow]Layer 5: LLM not available[/]")
        console.print("  Install with: [cyan]pip install taskfile[llm][/]")
        console.print(f"  ({len(llm_issues)} issue(s) could benefit from AI suggestions)")
        return

    console.print(f"\n[bold magenta]Layer 5: Asking AI about {len(llm_issues)} issue(s)...[/]")
    suggestions = diagnostics.llm_repair()
    for suggestion in suggestions:
        console.print(f"  💡 {suggestion}")


def _ssh_run(
    ssh_cmd: str, remote_cmd: str, timeout: int = 10
) -> subprocess.CompletedProcess | None:
    """Run a single command over SSH. Returns CompletedProcess or None on timeout/error."""
    try:
        return subprocess.run(
            f"{ssh_cmd} '{remote_cmd}'",
            shell=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None


def _check_remote_podman(ssh_cmd: str, host: str) -> None:
    """Check podman version on remote host."""
    result = _ssh_run(ssh_cmd, 'podman --version 2>/dev/null || echo "NOT_INSTALLED"')
    if result and result.returncode == 0 and "NOT_INSTALLED" not in result.stdout:
        version = result.stdout.strip().replace("podman version ", "").replace("Version: ", "")
        console.print(f"[green]  ✓ Podman: {version}[/]")
    else:
        console.print(f"[yellow]  ⚠ Podman not installed on {host}[/]")


def _check_remote_disk(ssh_cmd: str) -> None:
    """Check disk space on remote host."""
    result = _ssh_run(ssh_cmd, "df -h / | tail -1")
    if result and result.returncode == 0:
        parts = result.stdout.strip().split()
        if len(parts) >= 5:
            console.print(f"[dim]  Disk: {parts[4]} used ({parts[2]} / {parts[1]})[/]")


def _check_remote_memory(ssh_cmd: str) -> None:
    """Check memory on remote host."""
    result = _ssh_run(ssh_cmd, 'free -h 2>/dev/null | grep Mem || echo "N/A"')
    if result and result.returncode == 0 and result.stdout.strip() != "N/A":
        mem_parts = result.stdout.strip().split()
        if len(mem_parts) >= 4:
            console.print(f"[dim]  Memory: {mem_parts[2]} used / {mem_parts[1]} total[/]")


def _check_remote_containers(ssh_cmd: str) -> None:
    """Check running container and image counts on remote host."""
    result = _ssh_run(ssh_cmd, "podman ps -q 2>/dev/null | wc -l")
    if result and result.returncode == 0:
        console.print(f"[dim]  Running containers: {result.stdout.strip()}[/]")

    result = _ssh_run(ssh_cmd, "podman images -q 2>/dev/null | wc -l")
    if result and result.returncode == 0:
        console.print(f"[dim]  Stored images: {result.stdout.strip()}[/]")


def _resolve_selected_env() -> str | None:
    """Read --env flag from parent click context (taskfile --env prod doctor --remote)."""
    ctx = click.get_current_context(silent=True)
    if not ctx:
        return None
    parent = ctx.parent
    while parent:
        selected = (parent.params or {}).get("env_name")
        if selected:
            return selected
        parent = parent.parent
    return None


def _collect_remote_envs(config, selected_env: str | None) -> list[tuple] | None:
    """Build list of remote environments to check. Returns None on user-facing error."""
    if selected_env:
        env_obj = config.environments.get(selected_env)
        if env_obj and env_obj.is_remote:
            return [(selected_env, env_obj)]
        if env_obj:
            console.print(f"[yellow]  Environment '{selected_env}' is not remote (no ssh_host)[/]")
        else:
            console.print(f"[yellow]  Environment '{selected_env}' not found in Taskfile.yml[/]")
        return None
    envs = [(name, env) for name, env in config.environments.items() if env.is_remote]
    if not envs:
        console.print("[yellow]  No remote environments configured in Taskfile.yml[/]")
        return None
    return envs


def _run_fixop_checks(env) -> None:
    """Run extended fixop infrastructure checks on a remote environment.

    Checks: DNS, container DNS, UFW forward policy, systemd-resolved, NAT masquerade.
    Degrades gracefully when fixop is not installed.
    """
    try:
        import fixop
    except ImportError:
        return  # fixop not installed — skip silently

    ctx = fixop.HostContext(
        host=env.ssh_host,
        user=env.ssh_user or "root",
        port=env.ssh_port or 22,
        key=getattr(env, "ssh_key", None) or "~/.ssh/id_ed25519",
    )

    _CHECKS = [
        ("DNS", fixop.check_host_dns),
        ("systemd-resolved", fixop.check_systemd_resolved),
        ("UFW forward policy", fixop.check_ufw_forward_policy),
    ]

    found = 0
    for label, check_fn in _CHECKS:
        try:
            issues = check_fn(ctx)
            for issue in issues:
                sev = issue.severity.value
                color = "red" if sev in ("error", "critical") else "yellow"
                console.print(f"[{color}]  ⚠ [{label}] {issue.message}[/{color}]")
                if issue.fix_command:
                    console.print(f"[dim]    Fix: {issue.fix_command}[/]")
                found += 1
        except Exception:
            pass  # individual check failure — skip

    if found == 0:
        console.print("[green]  ✓ Infrastructure checks passed (DNS, UFW, systemd-resolved)[/]")


def _diagnose_single_remote_env(env_name, env, taskfile_dir) -> None:
    """Run all remote diagnostics for a single environment."""
    from taskfile.deploy_utils import test_ssh_connection
    from taskfile.diagnostics.checks import _resolve_env_fields

    _resolve_env_fields(env, taskfile_dir)
    console.print(f"\n[bold]Environment: {env_name}[/] ({env.ssh_host})")

    ssh_result = test_ssh_connection(env.ssh_host, env.ssh_user, env.ssh_port)
    if not ssh_result.success:
        detail = (
            ssh_result.output.strip()
            if ssh_result.output and ssh_result.output.strip()
            else f"exit code {ssh_result.exit_code}"
        )
        console.print(f"[red]  ✗ SSH connection failed: {detail}[/]")
        console.print(f"[dim]    ssh {env.ssh_opts} {env.ssh_user}@{env.ssh_host} 'echo ok'[/]")
        return

    console.print(f"[green]  ✓ SSH connected to {env.ssh_host}[/]")
    ssh_cmd = f"ssh {env.ssh_opts} {env.ssh_user}@{env.ssh_host}"

    try:
        _check_remote_podman(ssh_cmd, env.ssh_host)
        _check_remote_disk(ssh_cmd)
        _check_remote_memory(ssh_cmd)
        _check_remote_containers(ssh_cmd)
    except Exception as e:
        console.print(f"[yellow]  Remote diagnostics error: {e}[/]")

    # Extended infrastructure checks via fixop (DNS, UFW, TLS, systemd-resolved, NAT)
    _run_fixop_checks(env)


def _run_remote_diagnostics(diagnostics: ProjectDiagnostics) -> None:
    """Extended remote diagnostics — check containers, images, system status on remote server."""
    from taskfile.parser import find_taskfile

    console.print("\n[bold cyan]🔍 Remote Server Diagnostics[/]")

    try:
        tf = find_taskfile()
        config = load_taskfile(tf)
    except Exception:
        console.print("[yellow]  Could not load Taskfile config for remote diagnostics[/]")
        return

    selected_env = _resolve_selected_env()
    remote_envs = _collect_remote_envs(config, selected_env)
    if remote_envs is None:
        return

    for env_name, env in remote_envs:
        _diagnose_single_remote_env(env_name, env, tf.parent)


class _nullcontext:
    """Minimal no-op context manager for Python <3.10 compat."""

    def __enter__(self):
        return self

    def __exit__(self, *a):
        pass


def _run_examples_check(diagnostics: ProjectDiagnostics, report: bool) -> None:
    """Validate all examples/ directories and print results."""
    from taskfile.cli.diagnostics import IssueCategory

    examples_dir = Path("examples")
    if not examples_dir.is_dir():
        # Try relative to Taskfile
        try:
            tf = find_taskfile()
            examples_dir = tf.parent / "examples"
        except Exception:
            pass

    results = ProjectDiagnostics.check_examples(examples_dir)
    if not results:
        if not report:
            console.print("[yellow]No examples found to validate[/]")
        return

    if not report:
        from rich.table import Table
        from rich import box as rbox

        table = Table(title="Examples Validation", box=rbox.ROUNDED)
        table.add_column("Example", style="cyan")
        table.add_column("Tasks", justify="right")
        table.add_column("Envs", justify="right")
        table.add_column("Status")
        table.add_column("Missing .env files")

        for r in results:
            if r["errors"]:
                status = "[red]✗ Error[/]"
            elif r["missing_env_files"]:
                status = "[yellow]⚠ Warning[/]"
            else:
                status = "[green]✓ OK[/]"
            missing = ", ".join(r["missing_env_files"]) if r["missing_env_files"] else ""
            table.add_row(r["name"], str(r["tasks"]), str(r["envs"]), status, missing)

        console.print(table)

    # Add missing .env files as issues
    for r in results:
        for mf in r["missing_env_files"]:
            diagnostics._add_issue(
                f"Example '{r['name']}': missing {mf}", "warning", False, IssueCategory.ENV
            )
        for err in r["errors"]:
            diagnostics._add_issue(
                f"Example '{r['name']}': {err}", "error", False, IssueCategory.CONFIG
            )


def _apply_init_extras(choices: dict) -> None:
    """Write env files, .gitignore, and init git based on wizard choices."""
    env_config = choices.get("env_config") or {}
    if env_config:
        _write_env_file(env_config, "local")
        staging_config = {k: v for k, v in env_config.items() if "STAGING" in k or "PROD" in k}
        if staging_config and any(k.startswith("STAGING_") for k in env_config):
            _write_env_file(staging_config, "prod")

    if choices.get("create_gitignore"):
        _create_gitignore()

    if choices.get("init_git"):
        try:
            subprocess.run(["git", "init"], capture_output=True, check=True)
            console.print("[green]✓ Initialized git repository[/]")
        except Exception as e:
            console.print(f"[yellow]⚠ Git init failed: {e}[/]")


@main.command()
@click.option(
    "--template",
    type=click.Choice(
        [
            "minimal",
            "web",
            "podman",
            "codereview",
            "full",
            "saas",
            "multiplatform",
            "publish",
            "kubernetes",
            "terraform",
            "iot",
        ]
    ),
    default=None,
    help="Project template",
)
@click.option(
    "--from-doql",
    "from_doql",
    type=click.Path(exists=True, dir_okay=False),
    default=None,
    help="Generate Taskfile.yml from a .doql.css spec instead of a template",
)
@click.option("--force", is_flag=True, help="Overwrite existing files")
@click.option("--interactive", "-i", is_flag=True, help="Interactive setup with prompts")
def init(template, from_doql, force, interactive):
    """**✨ Create a new Taskfile.yml** with interactive setup.

    ## Templates

    | Template | Description |
    |----------|-------------|
    | `minimal` | Basic setup with build/test/run |
    | `web` | Web application with Docker |
    | `podman` | Podman/Quadlet deployment |
    | `kubernetes` | K8s deployment |
    | `full` | Complete CI/CD pipeline |

    ## Options

    | Option | Description |
    |--------|-------------|
    | `--template` | Project template to use |
    | `--force` | Overwrite existing files |
    | `-i, --interactive` | Interactive setup with prompts |

    ## Examples

    ```bash
    # Minimal template (default)
    taskfile init

    # Web app template
    taskfile init --template web

    # Full interactive setup
    taskfile init -i

    # Overwrite existing
    taskfile init -i --force
    ```
    """
    outpath = Path("Taskfile.yml")

    if outpath.exists() and not force:
        console.print(f"[yellow]{outpath} already exists. Use --force to overwrite.[/]")
        if not Confirm.ask("Continue anyway?", default=False):
            sys.exit(1)

    # ── Branch 1: convert from a .doql.css spec ────────────────────
    if from_doql:
        from taskfile.scaffold.from_doql import generate_from_doql

        try:
            content = generate_from_doql(from_doql)
        except Exception as exc:  # noqa: BLE001 — report and abort cleanly
            console.print(f"[red]❌ Failed to parse {from_doql}: {exc}[/]")
            sys.exit(1)
        outpath.write_text(content)
        console.print(f"[green]✓ Created Taskfile.yml (from: {from_doql})[/]")
        choices = {"env_config": {}, "create_gitignore": False, "init_git": False}
        _apply_init_extras(choices)
        console.print("\n[bold green]✨ Project initialized from doql spec! 🚀[/]")
        console.print("\n[dim]Next steps:[/]")
        console.print("  taskfile doctor     — Check setup")
        console.print("  taskfile list       — See available tasks")
        return

    # ── Branch 2: interactive / template-driven generation ─────────
    if interactive or template is None:
        choices = _collect_init_choices()
        template = choices["template"]
    else:
        choices = {"env_config": {}, "create_gitignore": False, "init_git": False}

    # Generate Taskfile
    from taskfile.scaffold import generate_taskfile

    content = generate_taskfile(template)

    # Project-aware customisation — only for the minimal template, since the
    # other templates are already opinionated about their stack.
    if template == "minimal":
        try:
            from taskfile.scaffold.customize import customise_minimal

            content = customise_minimal(content, Path.cwd())
        except Exception as exc:  # noqa: BLE001 — never block init on detection
            console.print(
                f"[yellow]⚠ Project detection failed ({exc}); writing generic template.[/]"
            )

    outpath.write_text(content)
    console.print(f"[green]✓ Created Taskfile.yml (template: {template})[/]")

    _apply_init_extras(choices)

    # Summary
    console.print("\n[bold green]✨ Project initialized! 🚀[/]")
    console.print("\n[dim]Next steps:[/]")
    console.print("  taskfile doctor     — Check setup")
    console.print("  taskfile list       — See available tasks")
    console.print("  taskfile run build  — Build your project")
