"""Import/Export converters for taskfile - convert to/from other formats.

Note: For CLI ``taskfile import`` (YAML-producing importer), see ``taskfile.importer``.
This module provides a class-based API used by ``taskfile export`` and programmatic
import/export via ``import_file`` / ``export_file``.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

from taskfile.importer import _FILENAME_TYPE_MAP as _IMPORTER_FILENAME_MAP

if TYPE_CHECKING:
    from taskfile.models import TaskfileConfig, Task


class MakefileConverter:
    """Convert between Taskfile and Makefile."""
    
    @staticmethod
    def import_makefile(content: str) -> dict:
        """Parse Makefile and extract targets as tasks."""
        tasks = {}
        variables = {}
        
        lines = content.split('\n')
        current_target = None
        current_commands = []
        
        for line in lines:
            # Variables
            var_match = re.match(r'^([A-Z_][A-Z0-9_]*)\s*[:?]?=\s*(.+)$', line.strip())
            if var_match:
                variables[var_match.group(1)] = var_match.group(2)
                continue
            
            # Target definition
            target_match = re.match(r'^([a-zA-Z_-][a-zA-Z0-9_-]*):(.*)$', line.strip())
            if target_match:
                # Save previous target
                if current_target and current_commands:
                    tasks[current_target] = {
                        'commands': current_commands,
                        'deps': [],
                    }
                
                current_target = target_match.group(1)
                deps_str = target_match.group(2).strip()
                current_commands = []
                
                # Parse dependencies
                if deps_str:
                    deps = [d.strip() for d in deps_str.split()]
                    if current_target not in tasks:
                        tasks[current_target] = {'commands': [], 'deps': deps}
                    else:
                        tasks[current_target]['deps'] = deps
                
                continue
            
            # Command (indented with tab)
            if current_target and line.startswith('\t'):
                cmd = line[1:].strip()
                if cmd:
                    current_commands.append(cmd)
        
        # Save last target
        if current_target and current_commands:
            tasks[current_target] = {
                'commands': current_commands,
                'deps': tasks.get(current_target, {}).get('deps', []),
            }
        
        return {
            'version': '1',
            'name': 'imported-from-makefile',
            'variables': variables,
            'tasks': tasks,
        }
    
    @staticmethod
    def export_makefile(config: TaskfileConfig) -> str:
        """Export Taskfile to Makefile format."""
        lines = ['# Generated by taskfile export', '']
        
        # Variables
        for name, value in config.variables.items():
            lines.append(f'{name} = {value}')
        
        if config.variables:
            lines.append('')
        
        # Default target
        if config.tasks:
            default_task = list(config.tasks.keys())[0]
            lines.append(f'.PHONY: all')
            lines.append(f'all: {default_task}')
            lines.append('')
        
        # Targets
        for name, task in config.tasks.items():
            deps = ' '.join(task.deps) if task.deps else ''
            lines.append(f'.PHONY: {name}')
            lines.append(f'{name}:{f" {deps}" if deps else ""}')
            
            for cmd in task.commands:
                lines.append(f'\t{cmd}')
            
            lines.append('')
        
        return '\n'.join(lines)


class GitHubActionsConverter:
    """Convert between Taskfile and GitHub Actions workflows."""
    
    @staticmethod
    def import_workflow(content: str) -> dict:
        """Parse GitHub Actions workflow YAML."""
        import yaml
        
        data = yaml.safe_load(content)
        tasks = {}
        
        if not data or 'jobs' not in data:
            return {'version': '1', 'tasks': {}}
        
        for job_name, job in data['jobs'].items():
            if 'steps' not in job:
                continue
            
            commands = []
            for step in job['steps']:
                if 'run' in step:
                    commands.append(step['run'])
                elif 'uses' in step:
                    commands.append(f'# Action: {step["uses"]}')
            
            tasks[job_name] = {
                'commands': commands,
                'deps': [],
            }
        
        return {
            'version': '1',
            'name': data.get('name', 'imported-from-gha'),
            'tasks': tasks,
        }
    
    @staticmethod
    def export_workflow(config: TaskfileConfig, workflow_name: str = 'ci') -> str:
        """Export Taskfile to GitHub Actions workflow."""
        import yaml
        
        jobs = {}
        
        for name, task in config.tasks.items():
            steps = []
            
            # Checkout step
            steps.append({'uses': 'actions/checkout@v4'})
            
            # Setup step based on detected project type
            if any('npm' in cmd for cmd in task.commands):
                steps.append({
                    'uses': 'actions/setup-node@v4',
                    'with': {'node-version': '20'}
                })
                steps.append({'run': 'npm ci'})
            elif any('pip' in cmd or 'python' in cmd for cmd in task.commands):
                steps.append({
                    'uses': 'actions/setup-python@v5',
                    'with': {'python-version': '3.11'}
                })
            
            # Task commands
            for cmd in task.commands:
                steps.append({'run': cmd})
            
            jobs[name] = {
                'runs-on': 'ubuntu-latest',
                'steps': steps,
            }
            
            # Add needs if task has deps
            if task.deps:
                jobs[name]['needs'] = list(task.deps)
        
        workflow = {
            'name': workflow_name,
            'on': ['push', 'pull_request'],
            'jobs': jobs,
        }
        
        return yaml.dump(workflow, default_flow_style=False, sort_keys=False)


class NpmScriptsConverter:
    """Convert between Taskfile and npm scripts."""
    
    @staticmethod
    def import_package_json(content: str) -> dict:
        """Parse package.json and extract scripts as tasks."""
        import json
        
        data = json.loads(content)
        scripts = data.get('scripts', {})
        
        tasks = {}
        for name, script in scripts.items():
            # npm scripts are typically single commands or chained with &&
            commands = [cmd.strip() for cmd in script.split('&&') if cmd.strip()]
            
            tasks[name] = {
                'commands': commands,
                'deps': [],
            }
        
        return {
            'version': '1',
            'name': data.get('name', 'imported-from-npm'),
            'tasks': tasks,
        }
    
    @staticmethod
    def export_package_json(config: TaskfileConfig, project_name: str = 'my-project') -> str:
        """Export Taskfile to package.json scripts section."""
        import json
        
        scripts = {}
        
        for name, task in config.tasks.items():
            # Join commands with && for npm scripts
            script = ' && '.join(task.commands)
            scripts[name] = script
        
        package = {
            'name': project_name,
            'version': '1.0.0',
            'scripts': scripts,
        }
        
        return json.dumps(package, indent=2)


class GitLabCIConverter:
    """Convert between Taskfile and GitLab CI."""
    
    @staticmethod
    def import_gitlab_ci(content: str) -> dict:
        """Parse GitLab CI YAML and extract jobs as tasks."""
        import yaml
        
        data = yaml.safe_load(content)
        tasks = {}
        
        if not data:
            return {'version': '1', 'tasks': {}}
        
        # Extract jobs (excluding global keys like stages, variables, etc.)
        global_keys = {'stages', 'variables', 'cache', 'image', 'services', 'before_script', 'after_script', 'default', 'include', 'workflow', 'artifacts'}
        
        for job_name, job in data.items():
            if job_name in global_keys:
                continue
                
            if not isinstance(job, dict):
                continue
            
            commands = []
            
            # Add before_script if present
            if 'before_script' in job:
                before_script = job['before_script']
                if isinstance(before_script, list):
                    commands.extend(before_script)
                else:
                    commands.append(str(before_script))
            
            # Add script
            if 'script' in job:
                script = job['script']
                if isinstance(script, list):
                    commands.extend(script)
                else:
                    commands.append(str(script))
            
            # Add after_script if present
            if 'after_script' in job:
                after_script = job['after_script']
                if isinstance(after_script, list):
                    commands.extend(after_script)
                else:
                    commands.append(str(after_script))
            
            # Handle dependencies via 'needs' or 'dependencies'
            deps = []
            if 'needs' in job:
                needs = job['needs']
                if isinstance(needs, list):
                    deps.extend(needs)
                else:
                    deps.append(str(needs))
            elif 'dependencies' in job:
                dependencies = job['dependencies']
                if isinstance(dependencies, list):
                    deps.extend(dependencies)
                else:
                    deps.append(str(dependencies))
            
            tasks[job_name] = {
                'commands': commands,
                'deps': deps,
            }
        
        return {
            'version': '1',
            'name': 'imported-from-gitlab-ci',
            'tasks': tasks,
        }


class DockerComposeConverter:
    """Convert Taskfile docker tasks to docker-compose services."""
    
    @staticmethod
    def export_docker_compose(config: TaskfileConfig) -> str:
        """Export Taskfile to docker-compose.yml format."""
        import yaml
        
        services = {}
        
        for name, task in config.tasks.items():
            # Look for docker/podman commands
            for cmd in task.commands:
                if 'docker run' in cmd or 'podman run' in cmd:
                    # Parse docker run command
                    # This is a simplified parser
                    image_match = re.search(r'(docker|podman) run.*(?:--name\s+(\S+)).*(\S+:\S+)', cmd)
                    if image_match:
                        image = image_match.group(3)
                        container_name = image_match.group(2) or name
                        
                        services[name] = {
                            'image': image,
                            'container_name': container_name,
                        }
                        
                        # Parse ports
                        port_match = re.findall(r'-p\s+(\d+:\d+)', cmd)
                        if port_match:
                            services[name]['ports'] = port_match
                        
                        break
        
        compose = {'services': services} if services else {}
        
        return yaml.dump(compose, default_flow_style=False)


def detect_format(file_path: Path) -> str | None:
    """Detect file format from path.

    Reuses the shared filename→type map from ``taskfile.importer`` for
    Makefile / GitLab CI, and adds extra types (npm, docker-compose, python)
    that only the converter layer needs.
    """
    name = file_path.name.lower()

    # Shared exact-name lookup (makefile, gnumakefile, .gitlab-ci.yml/yaml)
    if name in _IMPORTER_FILENAME_MAP:
        return _IMPORTER_FILENAME_MAP[name]

    # Converter-specific types
    if name == 'package.json':
        return 'npm'
    if name.endswith('.sh'):
        return 'shell'
    if name.endswith('.py'):
        return 'python'

    # YAML files: infer from path / content hints
    if name.endswith(('.yml', '.yaml')):
        if '.github/workflows' in str(file_path):
            return 'github-actions'
        if 'docker-compose' in name:
            return 'docker-compose'
        return 'yaml'

    return None


def import_file(file_path: Path, source_type: str | None = None) -> dict:
    """Import a file into Taskfile format.
    
    Args:
        file_path: Path to source file
        source_type: Type of source file (auto-detected if None)
        
    Returns:
        Dict representing Taskfile configuration
    """
    content = file_path.read_text()
    
    if source_type is None:
        source_type = detect_format(file_path)
    
    if source_type == 'makefile':
        return MakefileConverter.import_makefile(content)
    elif source_type == 'github-actions':
        return GitHubActionsConverter.import_workflow(content)
    elif source_type == 'gitlab-ci':
        return GitLabCIConverter.import_gitlab_ci(content)
    elif source_type == 'npm':
        return NpmScriptsConverter.import_package_json(content)
    else:
        raise ValueError(f"Unsupported source type: {source_type}")


def export_file(config: TaskfileConfig, target_type: str, **kwargs) -> str:
    """Export Taskfile to another format.
    
    Args:
        config: Taskfile configuration
        target_type: Target format (makefile, github-actions, npm, docker-compose)
        **kwargs: Additional arguments for specific converters
        
    Returns:
        String in target format
    """
    if target_type == 'makefile':
        return MakefileConverter.export_makefile(config)
    elif target_type == 'github-actions':
        return GitHubActionsConverter.export_workflow(config, kwargs.get('workflow_name', 'ci'))
    elif target_type == 'npm':
        return NpmScriptsConverter.export_package_json(config, kwargs.get('project_name', 'my-project'))
    elif target_type == 'docker-compose':
        return DockerComposeConverter.export_docker_compose(config)
    else:
        raise ValueError(f"Unsupported target type: {target_type}")
