version: '1'
name: alpha

tasks:
  install:
    desc: Install dependencies
    cmds:
    - echo "alpha: install"

  test:
    desc: Run tests
    cmds:
    - echo "alpha: test"

  lint:
    desc: Lint
    cmds:
    - echo "alpha: lint"

  build:
    desc: Build artifact
    cmds:
    - echo "alpha: build"
