flowchart LR
    subgraph examples_script_extraction
        examples__main["main"]
        examples__ssh_run["ssh_run"]
        examples__script_extraction__scripts__release__run["run"]
        examples__main["main"]
    end
    subgraph src_taskfile
        src__taskfile__cli__diagnostics___upsert_env_value["_upsert_env_value"]
        src__taskfile__compose__resolve_dict["resolve_dict"]
        src___stop_conflicting_containers["_stop_conflicting_containers"]
        src___quadlet_step3_reload_and_pull["_quadlet_step3_reload_and_pull"]
        src__taskfile__quadlet___parse_memory_limit["_parse_memory_limit"]
        src__taskfile__quadlet___build_service_section["_build_service_section"]
        src__taskfile__cli__setup___validate_ssh_key["_validate_ssh_key"]
        src__taskfile__importer___detect_type["_detect_type"]
        src__taskfile__importer___import_dockerfile["_import_dockerfile"]
        src___execute_commands["_execute_commands"]
        src__check_taskfile["check_taskfile"]
        src__taskfile__importer___dump_taskfile["_dump_taskfile"]
        src__taskfile__quadlet___parse_cpus_limit["_parse_cpus_limit"]
        src__taskfile__cli__deploy___deploy_remote_compose["_deploy_remote_compose"]
        src__taskfile__parser__validate_taskfile["validate_taskfile"]
        src___detect_project_type["_detect_project_type"]
        src__taskfile__runner__commands__execute_commands["execute_commands"]
        src__taskfile__compose__load_env_file["load_env_file"]
        src__taskfile__cli__deploy___ssh["_ssh"]
        src__taskfile__quadlet___build_container_networks["_build_container_networks"]
        src__taskfile__ssh__has_paramiko["has_paramiko"]
        src__taskfile__cli__auth__auth_setup["auth_setup"]
        src__taskfile__cli__main__validate["validate"]
        src__taskfile__fleet__FleetConfig__from_dict["from_dict"]
        src__taskfile__graph__detect_cycles["detect_cycles"]
        src__taskfile__quadlet___generate_volume_files["_generate_volume_files"]
        src__taskfile__fleet__deploy_to_device["deploy_to_device"]
        src__taskfile__notifications___notify_linux["_notify_linux"]
        src__taskfile__cli__fleet___safe_ssh["_safe_ssh"]
        src__taskfile__quadlet___build_container_volumes["_build_container_volumes"]
        src__taskfile__cli__import_export__export_cmd["export_cmd"]
        src___build_container_podman_args["_build_container_podman_args"]
        src__taskfile__cli__setup___validate_ip["_validate_ip"]
        src__taskfile__quadlet___build_container_section["_build_container_section"]
        src__taskfile__cli__release___step_upload_releases["_step_upload_releases"]
        src___find_free_port_near["_find_free_port_near"]
        src__taskfile__cli__deploy___deploy_local_compose["_deploy_local_compose"]
        src__taskfile__cache__get_project_hash["get_project_hash"]
        src__taskfile__quadlet___generate_container_files["_generate_container_files"]
        src__taskfile__parser___validate_task_commands["_validate_task_commands"]
        src__taskfile__models__TaskfileConfig__from_dict["from_dict"]
        src__taskfile__cli__deploy___resolve_deploy_config["_resolve_deploy_config"]
        src__taskfile__health__print_health_report["print_health_report"]
        src__taskfile__quadlet___build_container_env["_build_container_env"]
        src__taskfile__parser__load_taskfile["load_taskfile"]
        src__taskfile__cli__diagnostics___is_port_free["_is_port_free"]
        src__taskfile__cli__deploy___deploy_quadlet["_deploy_quadlet"]
        src__taskfile__quadlet___generate_network_file["_generate_network_file"]
        src___quadlet_step1_generate["_quadlet_step1_generate"]
        src__taskfile__fleet___deploy_canary["_deploy_canary"]
        src__generate["generate"]
        src__taskfile__watch__watch_tasks["watch_tasks"]
        src__taskfile__cli__ci__ci_generate["ci_generate"]
        src__taskfile__cli__release___step_build_desktop["_step_build_desktop"]
        src__taskfile__graph__print_task_tree["print_task_tree"]
        src__taskfile__parser___resolve_includes["_resolve_includes"]
        src__taskfile__cli__fleet__fleet_repair_cmd["fleet_repair_cmd"]
        src__taskfile__cli__version___get_version_from_git["_get_version_from_git"]
        src___init_config["_init_config"]
        src__taskfile__cli__release___show_release_plan["_show_release_plan"]
        src__taskfile__parser__scan_nearby_taskfiles["scan_nearby_taskfiles"]
        src__taskfile__runner__commands__execute_script["execute_script"]
        src__taskfile__cli__interactive__graph["graph"]
        src__taskfile__health__check_ssh_service["check_ssh_service"]
        src__taskfile__fleet__check_device_status["check_device_status"]
        src__taskfile__cli__version__set["set"]
        src___select_deploy_strategy["_select_deploy_strategy"]
        src__taskfile__cli__completion__get_task_names["get_task_names"]
        src__taskfile__quadlet__generate_network_unit["generate_network_unit"]
        src__taskfile__cli__docker_cmds__docker_ps_cmd["docker_ps_cmd"]
        src__taskfile__fleet__load_fleet["load_fleet"]
        src__import_makefile["import_makefile"]
        src__taskfile__cli__version___increment_version["_increment_version"]
        src__taskfile__cli__main___group_rolling["_group_rolling"]
        src____init__["__init__"]
        src__taskfile__converters__export_file["export_file"]
        src__taskfile__cli__release___get_current_tag["_get_current_tag"]
        src__taskfile__cli__fleet__fleet_list_cmd["fleet_list_cmd"]
        src__taskfile__cigen__generate_ci["generate_ci"]
        src__taskfile__cli__cache_cmds__cache_clear["cache_clear"]
        src__taskfile__quadlet___build_container_labels["_build_container_labels"]
        src___serve_tasks_json["_serve_tasks_json"]
        src__taskfile__quadlet___collect_named_volumes["_collect_named_volumes"]
        src__taskfile__graph__export_to_dot["export_to_dot"]
        src__taskfile__health__health_check_all["health_check_all"]
        src__taskfile__cli__version___is_valid_version["_is_valid_version"]
        src__taskfile__cli__release___confirm_release["_confirm_release"]
        src__taskfile__cli__release___run_command["_run_command"]
        src__taskfile__models__PipelineConfig__from_dict["from_dict"]
        src__generate["generate"]
        src__taskfile__importer__import_file["import_file"]
        src__taskfile__ssh___ssh_exec_subprocess["_ssh_exec_subprocess"]
        src__taskfile__cigen__preview_ci["preview_ci"]
        src__taskfile__quadlet___parse_port["_parse_port"]
        src___parse_pipeline["_parse_pipeline"]
        src__taskfile__parser__find_taskfile["find_taskfile"]
        src__taskfile__cli__setup___execute_setup_steps["_execute_setup_steps"]
        src__taskfile__fleet___ssh_cmd["_ssh_cmd"]
        src__taskfile__cli__release___step_health_check["_step_health_check"]
        src__import_gitlab_ci["import_gitlab_ci"]
        src__taskfile__ssh___pool_key["_pool_key"]
        src__taskfile__cache__TaskCache__get_stats["get_stats"]
        src__taskfile__cli__version__show["show"]
        src__taskfile__notifications__notify_task_complete["notify_task_complete"]
        src___fix_ports["_fix_ports"]
        src__taskfile__runner__commands__run_command["run_command"]
        src__taskfile__cli__setup___parse_ports["_parse_ports"]
        src__taskfile__cli__info_cmd__info["info"]
        src__taskfile__cli__fleet__fleet_status_cmd["fleet_status_cmd"]
        src__generate["generate"]
        src__taskfile__quadlet___build_install_section["_build_install_section"]
        src__taskfile__landing__build_landing_page["build_landing_page"]
        src__taskfile__cli__main___print_nearby_taskfiles["_print_nearby_taskfiles"]
        src__taskfile__cli__ci__ci_run["ci_run"]
        src__taskfile__cli__release___step_deploy_web["_step_deploy_web"]
        src__taskfile__quadlet___build_unit_section["_build_unit_section"]
        src__taskfile__cli__setup__setup["setup"]
        src___strip_remote_prefix["_strip_remote_prefix"]
        src__taskfile__parser___validate_task_dependencies["_validate_task_dependencies"]
        src___serve_config_json["_serve_config_json"]
        src__get_environment_names["get_environment_names"]
        src__taskfile__cli__interactive___suggest_template["_suggest_template"]
        src___fix_taskfile["_fix_taskfile"]
        src__taskfile__health__check_http_endpoint["check_http_endpoint"]
        src__taskfile__cli__interactive__watch["watch"]
        src__taskfile__cli__deploy___run["_run"]
        src__taskfile__cli__main___run_env_group["_run_env_group"]
        src__taskfile__runner__ssh__run_embedded_ssh["run_embedded_ssh"]
        src___is_remote_command["_is_remote_command"]
        src__taskfile__cli__main__import_cmd["import_cmd"]
        src__taskfile__scaffold___load_template["_load_template"]
        src___update_taskfile_version["_update_taskfile_version"]
        src__taskfile__cigen__generate_all_ci["generate_all_ci"]
        src__taskfile__runner__ssh__strip_remote_prefix["strip_remote_prefix"]
        src___execute_deploy_strategy["_execute_deploy_strategy"]
        src__taskfile__cli__deploy__deploy_cmd["deploy_cmd"]
        src__taskfile__quadlet__compose_to_quadlet["compose_to_quadlet"]
        src__taskfile__runner__core__TaskfileRunner__run["run"]
        src___quadlet_step4_restart_and_cleanup["_quadlet_step4_restart_and_cle"]
        src__taskfile__cigen__base___yaml_dump["_yaml_dump"]
        src__taskfile__cli__auth__auth_verify["auth_verify"]
        src__taskfile__fleet___deploy_rolling["_deploy_rolling"]
        src__taskfile__cli__setup___provision_vps["_provision_vps"]
        src__taskfile__ssh__ssh_exec["ssh_exec"]
        src__taskfile__graph___add_deps_to_tree["_add_deps_to_tree"]
        src__taskfile__fleet___deploy_parallel["_deploy_parallel"]
        src___collect_init_choices["_collect_init_choices"]
        src__taskfile__cli__fleet___get_remote_envs["_get_remote_envs"]
        src__taskfile__cli__auth___check_tool["_check_tool"]
        src__taskfile__webui__serve_dashboard["serve_dashboard"]
        src__taskfile__cli__main__run["run"]
        src__taskfile__cli__ci__ci_list["ci_list"]
        src__taskfile__quadlet__generate_container_unit["generate_container_unit"]
        src__taskfile__compose__ComposeFile____init__["__init__"]
        src__import_workflow["import_workflow"]
        src__taskfile__cli__release___step_deploy_landing["_step_deploy_landing"]
        src__docker_stop_all_cmd["docker_stop_all_cmd"]
        src__taskfile__cli__docker_cmds___docker_stop["_docker_stop"]
        src__taskfile__cli__setup___provision_ssh_key["_provision_ssh_key"]
        src__taskfile__compose__resolve_variables["resolve_variables"]
        src__taskfile__cli__health__health_cmd["health_cmd"]
        src__run_inline_python["run_inline_python"]
        src___exec_function_python["_exec_function_python"]
        src__generate["generate"]
        src__export_workflow["export_workflow"]
        src__taskfile__notifications___notify_windows["_notify_windows"]
        src___containers_using_port["_containers_using_port"]
        src__taskfile__cli__interactive__serve["serve"]
        src__taskfile__importer___slugify["_slugify"]
        src__taskfile__cli__ci__ci_preview["ci_preview"]
        src__taskfile__cli__release___get_previous_tag["_get_previous_tag"]
        src__taskfile__cli__cache_cmds__cache_show["cache_show"]
        src__taskfile__scaffold__generate_taskfile["generate_taskfile"]
        src__taskfile__cli__deploy___quadlet_step2_upload["_quadlet_step2_upload"]
        src__taskfile__cli__quadlet___get_upload_env["_get_upload_env"]
        src__export_package_json["export_package_json"]
        src___execute_script["_execute_script"]
        src__taskfile__cli__auth___write_env_var["_write_env_var"]
        src__taskfile__converters__import_file["import_file"]
        src___update_pyproject_version["_update_pyproject_version"]
        src__taskfile__ssh___get_connection["_get_connection"]
        src__taskfile__landing__generate_landing_page["generate_landing_page"]
        src__taskfile__cli__setup___is_vps_ready["_is_vps_ready"]
        src__taskfile__cli__main__list_tasks["list_tasks"]
        src__taskfile__cli__setup___deploy_application["_deploy_application"]
        src__taskfile__cli__completion__get_platform_names["get_platform_names"]
        src__export_docker_compose["export_docker_compose"]
        src__taskfile__cli__ci__ci_targets["ci_targets"]
        src__taskfile__fleet___ping_device["_ping_device"]
        src__taskfile__cli__setup___build_config_from_args["_build_config_from_args"]
        src__taskfile__cli__interactive__init["init"]
        src__taskfile__health__run_health_checks["run_health_checks"]
        src__taskfile__notifications___notify_macos["_notify_macos"]
        src__taskfile__converters__detect_format["detect_format"]
        src__check_ports["check_ports"]
        src__taskfile__cli__release__rollback["rollback"]
        src__taskfile__cli__init_cmd__init["init"]
        src__taskfile__quadlet___build_container_ports["_build_container_ports"]
        src__taskfile__cli__auth___read_env_file["_read_env_file"]
        src__taskfile__quadlet__generate_volume_unit["generate_volume_unit"]
        src__taskfile__graph__build_dependency_graph["build_dependency_graph"]
        src__taskfile__graph__print_dependency_list["print_dependency_list"]
        src__taskfile__parser___validate_tasks_exist["_validate_tasks_exist"]
        src___resolve_release_config["_resolve_release_config"]
        src__taskfile__cli__fleet___ssh_check["_ssh_check"]
        src___run_inline_python["_run_inline_python"]
        src__taskfile__cli__fleet___load_config_or_exit["_load_config_or_exit"]
        src__taskfile__cli__release__release["release"]
        src__taskfile__importer___import_shell_script["_import_shell_script"]
        src__taskfile__runner__ssh__is_remote_command["is_remote_command"]
        src__taskfile__runner__ssh__wrap_ssh["wrap_ssh"]
        src___resolve_stages["_resolve_stages"]
        src__taskfile__cigen__list_targets["list_targets"]
        src__taskfile__cli__setup___test_ssh_connection["_test_ssh_connection"]
        src__taskfile__importer___import_github_actions["_import_github_actions"]
        src__taskfile__cli__quadlet___get_upload_files["_get_upload_files"]
        src__taskfile__cigen__base___sanitize_id["_sanitize_id"]
        src__import_package_json["import_package_json"]
        src___run_embedded_ssh["_run_embedded_ssh"]
        src___wrap_ssh["_wrap_ssh"]
        src___docker_containers_using_port["_docker_containers_using_port"]
        src__taskfile__fleet__deploy_to_group["deploy_to_group"]
        src__taskfile__cli__quadlet___run_upload_commands["_run_upload_commands"]
        src__taskfile__importer___import_gitlab_ci["_import_gitlab_ci"]
        src__taskfile__parser___validate_task_env_filter["_validate_task_env_filter"]
        src___container_publishes_port["_container_publishes_port"]
        src__taskfile__cli__quadlet__quadlet_upload["quadlet_upload"]
        src__export_makefile["export_makefile"]
        src__taskfile__cli__deploy___print_deploy_header["_print_deploy_header"]
        src__docker_stop_port_cmd["docker_stop_port_cmd"]
        src___run_function["_run_function"]
        src___update_env_with_free_ports["_update_env_with_free_ports"]
        src__taskfile__cli__version__bump["bump"]
        src__taskfile__cli__auth___ensure_gitignore["_ensure_gitignore"]
        src__taskfile__runner__functions__run_function["run_function"]
        src__taskfile__importer___import_makefile["_import_makefile"]
        src__taskfile__cli__docker_cmds___docker_ps["_docker_ps"]
    end
    src__taskfile__converters__import_file --> src__taskfile__converters__detect_format
    src__taskfile__converters__import_file --> src__import_makefile
    src__taskfile__converters__import_file --> src__import_workflow
    src__taskfile__converters__import_file --> src__import_gitlab_ci
    src__taskfile__converters__import_file --> src__import_package_json
    src__taskfile__converters__export_file --> src__export_makefile
    src__taskfile__converters__export_file --> src__export_workflow
    src__taskfile__converters__export_file --> src__export_package_json
    src__taskfile__converters__export_file --> src__export_docker_compose
    src__taskfile__importer__import_file --> src__taskfile__importer___detect_type
    src__taskfile__importer__import_file --> src__taskfile__importer___import_github_actions
    src__taskfile__importer__import_file --> src__taskfile__importer___import_gitlab_ci
    src__taskfile__importer__import_file --> src__taskfile__importer___import_makefile
    src__taskfile__importer__import_file --> src__taskfile__importer___import_shell_script
    src__taskfile__importer__import_file --> src__taskfile__importer___import_dockerfile
    src__taskfile__importer___import_github_actions --> src__taskfile__importer___dump_taskfile
    src__taskfile__importer___import_github_actions --> src__taskfile__importer___slugify
    src__taskfile__importer___import_gitlab_ci --> src__taskfile__importer___dump_taskfile
    src__taskfile__importer___import_makefile --> src__taskfile__importer___dump_taskfile
    src__taskfile__importer___import_shell_script --> src__taskfile__importer___dump_taskfile
    src__taskfile__importer___import_dockerfile --> src__taskfile__importer___dump_taskfile
    src__taskfile__importer___import_dockerfile --> src__taskfile__importer___slugify
    src__taskfile__landing__build_landing_page --> src__taskfile__landing__generate_landing_page
    src__taskfile__graph__detect_cycles --> src__taskfile__cli__version__set
    src__taskfile__graph__print_task_tree --> src__taskfile__graph__build_dependency_graph
    src__taskfile__graph__print_task_tree --> src__taskfile__graph__detect_cycles
    src__taskfile__graph__print_task_tree --> src__taskfile__graph___add_deps_to_tree
    src__taskfile__graph__print_task_tree --> src__taskfile__cli__version__set
    src__taskfile__graph__print_dependency_list --> src__taskfile__graph__build_dependency_graph
    src__taskfile__graph__export_to_dot --> src__taskfile__graph__build_dependency_graph
    src__taskfile__parser__find_taskfile --> src__taskfile__parser__scan_nearby_taskfiles
    src__taskfile__parser__load_taskfile --> src__taskfile__parser___resolve_includes
    src__taskfile__parser__load_taskfile --> src__taskfile__models__TaskfileConfig__from_dict
    src__taskfile__parser__load_taskfile --> src__taskfile__parser__find_taskfile
    src__taskfile__parser__validate_taskfile --> src__taskfile__parser___validate_tasks_exist
    src__taskfile__parser__validate_taskfile --> src__taskfile__parser___validate_task_commands
    src__taskfile__parser__validate_taskfile --> src__taskfile__parser___validate_task_dependencies
    src__taskfile__parser__validate_taskfile --> src__taskfile__parser___validate_task_env_filter
    src__taskfile__compose__resolve_dict --> src__taskfile__compose__resolve_variables
    src__taskfile__compose__ComposeFile____init__ --> src__taskfile__compose__resolve_dict
    src__taskfile__compose__ComposeFile____init__ --> src__taskfile__compose__load_env_file
    src__taskfile__health__run_health_checks --> src__taskfile__health__check_http_endpoint
    src__taskfile__health__run_health_checks --> src__taskfile__health__check_ssh_service
    src__taskfile__health__health_check_all --> src__taskfile__health__run_health_checks
    src__taskfile__health__health_check_all --> src__taskfile__health__print_health_report
    src___resolve_stages --> src__taskfile__cli__version__set
    src__taskfile__fleet__load_fleet --> src__taskfile__fleet__FleetConfig__from_dict
    src__taskfile__fleet__check_device_status --> src__taskfile__fleet___ping_device
    src__taskfile__fleet__check_device_status --> src__taskfile__fleet___ssh_cmd
    src__taskfile__fleet__deploy_to_device --> src__taskfile__fleet___ssh_cmd
    src__taskfile__fleet__deploy_to_group --> src__taskfile__fleet___deploy_rolling
    src__taskfile__fleet__deploy_to_group --> src__taskfile__fleet___deploy_canary
    src__taskfile__fleet__deploy_to_group --> src__taskfile__fleet___deploy_parallel
    src__taskfile__fleet___deploy_rolling --> src__taskfile__fleet__deploy_to_device
    src__taskfile__fleet___deploy_canary --> src__taskfile__fleet__deploy_to_device
    src__taskfile__ssh___get_connection --> src__taskfile__ssh___pool_key
    src__taskfile__ssh__ssh_exec --> src__taskfile__ssh___ssh_exec_subprocess
    src__taskfile__ssh__ssh_exec --> src__taskfile__ssh___get_connection
    src__taskfile__notifications__notify_task_complete --> src__taskfile__notifications___notify_macos
    src__taskfile__notifications__notify_task_complete --> src__taskfile__notifications___notify_linux
    src__taskfile__notifications__notify_task_complete --> src__taskfile__notifications___notify_windows
    src___serve_tasks_json --> src__taskfile__parser__load_taskfile
    src___serve_config_json --> src__taskfile__parser__load_taskfile
    src__taskfile__cache__TaskCache__get_stats --> src__taskfile__cli__version__set
    src__taskfile__cache__get_project_hash --> src__taskfile__parser__find_taskfile
    src__taskfile__scaffold__generate_taskfile --> src__taskfile__scaffold___load_template
    src___parse_pipeline --> src__taskfile__models__PipelineConfig__from_dict
    src__taskfile__runner__commands__run_command --> src__taskfile__runner__ssh__is_remote_command
    src__taskfile__runner__commands__run_command --> src__taskfile__runner__functions__run_function
    src__taskfile__runner__commands__run_command --> src__run_inline_python
    src__taskfile__runner__commands__run_command --> src__taskfile__runner__ssh__wrap_ssh
    src__taskfile__runner__commands__execute_commands --> src__taskfile__runner__commands__execute_script
    src__taskfile__runner__commands__execute_commands --> src__taskfile__runner__commands__run_command
    src__taskfile__runner__functions__run_function --> src___exec_function_python
    src__taskfile__runner__ssh__wrap_ssh --> src__taskfile__runner__ssh__strip_remote_prefix
    src__taskfile__runner__ssh__run_embedded_ssh --> src__taskfile__runner__ssh__strip_remote_prefix
    src__taskfile__runner__ssh__run_embedded_ssh --> src__taskfile__ssh__ssh_exec
    src__taskfile__cli__init_cmd__init --> src__taskfile__scaffold__generate_taskfile
    src__taskfile__cli__version__bump --> src__taskfile__cli__version___increment_version
    src__taskfile__cli__version__bump --> src___update_taskfile_version
    src__taskfile__cli__version__show --> src__taskfile__parser__find_taskfile
    src__taskfile__cli__version__show --> src__taskfile__cli__version___get_version_from_git
    src__taskfile__cli__version__set --> src___update_taskfile_version
    src__taskfile__cli__version__set --> src___update_pyproject_version
    src__taskfile__cli__version__set --> src__taskfile__cli__version___is_valid_version
    src____init__ --> src__taskfile__cli__version__set
    src____init__ --> src__taskfile__ssh__has_paramiko
    src___init_config --> src__taskfile__parser__load_taskfile
    src___is_remote_command --> src__taskfile__runner__ssh__is_remote_command
    src___strip_remote_prefix --> src__taskfile__runner__ssh__strip_remote_prefix
    src___wrap_ssh --> src__taskfile__runner__ssh__wrap_ssh
    src___run_embedded_ssh --> src__taskfile__runner__ssh__run_embedded_ssh
    src___run_function --> src__taskfile__runner__functions__run_function
    src___run_inline_python --> src__run_inline_python
    src___execute_script --> src__taskfile__runner__commands__execute_script
    src___execute_commands --> src__taskfile__runner__commands__execute_commands
    src__taskfile__runner__core__TaskfileRunner__run --> src__taskfile__parser__validate_taskfile
    src__taskfile__runner__core__TaskfileRunner__run --> src__taskfile__notifications__notify_task_complete
    src___containers_using_port --> src__taskfile__cli__docker_cmds___docker_ps
    src___containers_using_port --> src___container_publishes_port
    src__taskfile__cli__docker_cmds__docker_ps_cmd --> src__taskfile__cli__docker_cmds___docker_ps
    src__docker_stop_port_cmd --> src___containers_using_port
    src__docker_stop_port_cmd --> src__taskfile__cli__docker_cmds___docker_stop
    src__docker_stop_all_cmd --> src__taskfile__cli__docker_cmds___docker_ps
    src__docker_stop_all_cmd --> src__taskfile__cli__docker_cmds___docker_stop
    src__taskfile__cli__auth___write_env_var --> src__taskfile__cli__auth___read_env_file
    src__taskfile__cli__auth__auth_setup --> src__taskfile__cli__auth___ensure_gitignore
    src__taskfile__cli__auth__auth_verify --> src__taskfile__cli__auth___read_env_file
    src__taskfile__cli__auth__auth_verify --> src__taskfile__cli__auth___check_tool
    src__taskfile__cli__import_export__export_cmd --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__import_export__export_cmd --> src__taskfile__converters__export_file
    src___collect_init_choices --> src___detect_project_type
    src___collect_init_choices --> src__taskfile__cli__interactive___suggest_template
    src__taskfile__cli__interactive__init --> src__taskfile__scaffold__generate_taskfile
    src__taskfile__cli__interactive__watch --> src__taskfile__watch__watch_tasks
    src__taskfile__cli__interactive__graph --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__interactive__graph --> src__taskfile__graph__export_to_dot
    src__taskfile__cli__interactive__serve --> src__taskfile__webui__serve_dashboard
    src__taskfile__cli__health__health_cmd --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__health__health_cmd --> src__taskfile__health__run_health_checks
    src__taskfile__cli__health__health_cmd --> src__taskfile__health__print_health_report
    src__check_taskfile --> src__taskfile__parser__find_taskfile
    src__check_taskfile --> src__taskfile__parser__load_taskfile
    src__check_ports --> src__taskfile__compose__load_env_file
    src___fix_taskfile --> src__taskfile__scaffold__generate_taskfile
    src___fix_ports --> src__taskfile__cli__version__set
    src___stop_conflicting_containers --> src___docker_containers_using_port
    src___stop_conflicting_containers --> src__taskfile__cli__docker_cmds___docker_stop
    src___update_env_with_free_ports --> src__taskfile__cli__diagnostics___upsert_env_value
    src___find_free_port_near --> src__taskfile__cli__diagnostics___is_port_free
    src__taskfile__cli__ci__ci_generate --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__ci__ci_run --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__ci__ci_list --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__ci__ci_preview --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__ci__ci_preview --> src__taskfile__cigen__preview_ci
    src__taskfile__cli__ci__ci_targets --> src__taskfile__cigen__list_targets
    src__taskfile__cli__cache_cmds__cache_show --> src__taskfile__cache__get_project_hash
    src__taskfile__cli__cache_cmds__cache_clear --> src__taskfile__cache__get_project_hash
    src__taskfile__cli__setup___build_config_from_args --> src__taskfile__cli__setup___validate_ip
    src__taskfile__cli__setup___build_config_from_args --> src__taskfile__cli__setup___validate_ssh_key
    src__taskfile__cli__setup___execute_setup_steps --> src__taskfile__cli__setup___provision_ssh_key
    src__taskfile__cli__setup___execute_setup_steps --> src__taskfile__cli__setup___test_ssh_connection
    src__taskfile__cli__setup___execute_setup_steps --> src__taskfile__cli__setup___is_vps_ready
    src__taskfile__cli__setup___execute_setup_steps --> src__taskfile__cli__setup___deploy_application
    src__taskfile__cli__setup___execute_setup_steps --> src__taskfile__cli__setup___provision_vps
    src__taskfile__cli__setup__setup --> src__taskfile__cli__setup___parse_ports
    src___resolve_release_config --> src__taskfile__parser__load_taskfile
    src___resolve_release_config --> src__taskfile__cli__release___get_current_tag
    src__taskfile__cli__release___step_build_desktop --> src__taskfile__cli__release___run_command
    src__taskfile__cli__release___step_deploy_web --> src__taskfile__cli__release___run_command
    src__taskfile__cli__release___step_upload_releases --> src__taskfile__cli__release___run_command
    src__taskfile__cli__release___step_deploy_landing --> src__taskfile__landing__build_landing_page
    src__taskfile__cli__release___step_deploy_landing --> src__taskfile__cli__release___run_command
    src__taskfile__cli__release___step_health_check --> src__taskfile__health__health_check_all
    src__taskfile__cli__release__release --> src___resolve_release_config
    src__taskfile__cli__release__release --> src__taskfile__cli__release___show_release_plan
    src__taskfile__cli__release__release --> src__taskfile__cli__release___confirm_release
    src__taskfile__cli__release__rollback --> src__taskfile__cli__release___run_command
    src__taskfile__cli__release__rollback --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__release__rollback --> src__taskfile__cli__release___get_previous_tag
    src__taskfile__cli__completion__get_task_names --> src__taskfile__parser__load_taskfile
    src__get_environment_names --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__completion__get_platform_names --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__deploy___ssh --> src__taskfile__cli__deploy___run
    src__taskfile__cli__deploy___deploy_local_compose --> src__taskfile__cli__deploy___run
    src__taskfile__cli__deploy___deploy_remote_compose --> src__taskfile__cli__deploy___ssh
    src___quadlet_step1_generate --> src__taskfile__quadlet__compose_to_quadlet
    src__taskfile__cli__deploy___quadlet_step2_upload --> src__taskfile__cli__deploy___ssh
    src__taskfile__cli__deploy___quadlet_step2_upload --> src__taskfile__cli__deploy___run
    src___quadlet_step3_reload_and_pull --> src__taskfile__cli__deploy___ssh
    src___quadlet_step4_restart_and_cleanup --> src__taskfile__cli__deploy___ssh
    src__taskfile__cli__deploy___deploy_quadlet --> src___quadlet_step1_generate
    src__taskfile__cli__deploy___deploy_quadlet --> src__taskfile__cli__deploy___quadlet_step2_upload
    src__taskfile__cli__deploy___deploy_quadlet --> src___quadlet_step3_reload_and_pull
    src__taskfile__cli__deploy___deploy_quadlet --> src___quadlet_step4_restart_and_cleanup
    src__taskfile__cli__deploy___resolve_deploy_config --> src__taskfile__parser__load_taskfile
    src___execute_deploy_strategy --> src__taskfile__cli__deploy___deploy_local_compose
    src___execute_deploy_strategy --> src__taskfile__cli__deploy___deploy_remote_compose
    src___execute_deploy_strategy --> src__taskfile__cli__deploy___deploy_quadlet
    src__taskfile__cli__deploy__deploy_cmd --> src__taskfile__cli__deploy___resolve_deploy_config
    src__taskfile__cli__deploy__deploy_cmd --> src__taskfile__cli__deploy___print_deploy_header
    src__taskfile__cli__deploy__deploy_cmd --> src___select_deploy_strategy
    src__taskfile__cli__deploy__deploy_cmd --> src___execute_deploy_strategy
    src__taskfile__cli__quadlet__quadlet_upload --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__quadlet__quadlet_upload --> src__taskfile__cli__quadlet___get_upload_env
    src__taskfile__cli__quadlet__quadlet_upload --> src__taskfile__cli__quadlet___get_upload_files
    src__taskfile__cli__quadlet__quadlet_upload --> src__taskfile__cli__quadlet___run_upload_commands
    src__taskfile__cli__info_cmd__info --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__fleet___load_config_or_exit --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__fleet__fleet_status_cmd --> src__taskfile__cli__fleet___load_config_or_exit
    src__taskfile__cli__fleet__fleet_status_cmd --> src__taskfile__cli__fleet___get_remote_envs
    src__taskfile__cli__fleet__fleet_repair_cmd --> src__taskfile__cli__fleet___load_config_or_exit
    src__taskfile__cli__fleet___safe_ssh --> src__taskfile__cli__fleet___ssh_check
    src__taskfile__cli__fleet__fleet_list_cmd --> src__taskfile__cli__fleet___load_config_or_exit
    src__generate --> src__taskfile__cigen__base___yaml_dump
    src__generate --> src__taskfile__cigen__base___sanitize_id
    src__taskfile__cigen__generate_all_ci --> src__taskfile__cigen__generate_ci
    examples__main --> examples__script_extraction__scripts__release__run
    examples__main --> examples__ssh_run
    src__taskfile__cli__main___run_env_group --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__main___run_env_group --> src__taskfile__cli__main___group_rolling
    src__taskfile__cli__main__run --> src__taskfile__cli__main___run_env_group
    src__taskfile__cli__main__list_tasks --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__main__list_tasks --> src__taskfile__cli__main___print_nearby_taskfiles
    src__taskfile__cli__main__validate --> src__taskfile__parser__load_taskfile
    src__taskfile__cli__main__validate --> src__taskfile__parser__validate_taskfile
    src__taskfile__cli__main__import_cmd --> src__taskfile__converters__import_file
    src__taskfile__quadlet___build_container_ports --> src__taskfile__quadlet___parse_port
    src___build_container_podman_args --> src__taskfile__quadlet___parse_memory_limit
    src___build_container_podman_args --> src__taskfile__quadlet___parse_cpus_limit
    src__taskfile__quadlet___build_container_section --> src__taskfile__quadlet___build_container_env
    src__taskfile__quadlet___build_container_section --> src__taskfile__quadlet___build_container_ports
    src__taskfile__quadlet___build_container_section --> src__taskfile__quadlet___build_container_volumes
    src__taskfile__quadlet___build_container_section --> src__taskfile__quadlet___build_container_networks
    src__taskfile__quadlet___build_container_section --> src__taskfile__quadlet___build_container_labels
    src__taskfile__quadlet___build_container_section --> src___build_container_podman_args
    src__taskfile__quadlet__generate_container_unit --> src__taskfile__quadlet___build_unit_section
    src__taskfile__quadlet__generate_container_unit --> src__taskfile__quadlet___build_container_section
    src__taskfile__quadlet__generate_container_unit --> src__taskfile__quadlet___build_service_section
    src__taskfile__quadlet__generate_container_unit --> src__taskfile__quadlet___build_install_section
    src__taskfile__quadlet___collect_named_volumes --> src__taskfile__cli__version__set
    src__taskfile__quadlet___generate_network_file --> src__taskfile__quadlet__generate_network_unit
    src__taskfile__quadlet___generate_container_files --> src__taskfile__cli__version__set
    src__taskfile__quadlet___generate_container_files --> src__taskfile__quadlet___collect_named_volumes
    src__taskfile__quadlet___generate_container_files --> src__taskfile__quadlet__generate_container_unit
    src__taskfile__quadlet___generate_volume_files --> src__taskfile__quadlet__generate_volume_unit
    src__taskfile__quadlet__compose_to_quadlet --> src__taskfile__quadlet___generate_container_files
    src__taskfile__quadlet__compose_to_quadlet --> src__taskfile__quadlet___generate_network_file
    src__taskfile__quadlet__compose_to_quadlet --> src__taskfile__quadlet___generate_volume_files
