flowchart TD
    examples_functions_embed["examples.functions-embed<br/>1 funcs"]
    examples_script_extraction["examples.script-extraction<br/>6 funcs"]
    src_taskfile["src.taskfile<br/>600 funcs"]
